### ISSUE TITLE
widget not working with vaadin 24.7.x in Spring Boot 3.4.x

### ISSUE THREAD

**Issue by fbiricotti** [Sergio70/AceEditorV14#350]
Hello,

I'm trying to use the widget in a Spring boot project (3.4.x) and Vaadin 24.7.x, but the widget doesn't show up because of a JS error:

    FlowClient-D2PiiGbX.js:349 Uncaught TypeError: $0.refreshEditor is not a function
        at Object.eval (eval at zu (FlowClient-D2PiiGbX.js:7491:13), <anonymous>:3:11)

Please note that I've already added the de/f0rce following line to the vaadin.allowed-packages line in the Application.properties file.
Any help will be highly appreciated!

Thank you

**Comment by fbiricotti** [comment]
Found the problem: the correct item to add in the vaadin.allowed-packages property is com.hilerio.ace !
